apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
        - name: web
          image: nareshacr10d.azurecr.io/frontend:IMAGE_TAG_HERE
          ports: [{ containerPort: 80 }]
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "250m", memory: "256Mi" }
          env:
            - name: CUSTOMER_SERVICE_URL
              value: http://customer-service.prod.svc.cluster.local:8000
            - name: ORDER_SERVICE_URL
              value: http://order-service.prod.svc.cluster.local:8000
            - name: PRODUCT_SERVICE_URL
              value: http://product-service.prod.svc.cluster.local:8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  type: LoadBalancer
  selector: { app: frontend }
  ports:
    - port: 80
      targetPort: 80
